{"name": "test_first_scenario", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 6", "trace": "def test_first_scenario():\n        a = 5\n        b = 6\n>       assert a == b\nE       assert 5 == 6\n\ntest_myfile.py:4: AssertionError"}, "start": 1754542918896, "stop": 1754542918896, "uuid": "9b545f69-d2b7-45c3-8e03-6a0e7f7cb33c", "historyId": "466951d9dadc81d2aeb6ad66f556d7e0", "testCaseId": "466951d9dadc81d2aeb6ad66f556d7e0", "fullName": "test_myfile#test_first_scenario", "labels": [{"name": "suite", "value": "test_myfile"}, {"name": "host", "value": "Eli"}, {"name": "thread", "value": "12440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_myfile"}], "titlePath": ["test_myfile.py"]}